export var dummyScores = [
{dbn: '01M292',
    num_of_sat_test_takers: '29',
    sat_critical_reading_avg_score: '355',
    sat_math_avg_score: '404',
    sat_writing_avg_score: '363',
    school_name: 'HENRY STREET SCHOOL FOR INTERNATIONAL STUDIES'},
{dbn: '01M448',
    num_of_sat_test_takers: '91',
    sat_critical_reading_avg_score: '383',
    sat_math_avg_score: '423',
    sat_writing_avg_score: '366',
    school_name: 'UNIVERSITY NEIGHBORHOOD HIGH SCHOOL'},
{dbn: '01M450',
    num_of_sat_test_takers: '70',
    sat_critical_reading_avg_score: '377',
    sat_math_avg_score: '402',
    sat_writing_avg_score: '370',
    school_name: 'EAST SIDE COMMUNITY SCHOOL'},
{dbn: '01M458',
    num_of_sat_test_takers: '7',
    sat_critical_reading_avg_score: '414',
    sat_math_avg_score: '401',
    sat_writing_avg_score: '359',
    school_name: 'FORSYTH SATELLITE ACADEMY'},
{dbn: '01M509',
    num_of_sat_test_takers: '44',
    sat_critical_reading_avg_score: '390',
    sat_math_avg_score: '433',
    sat_writing_avg_score: '384',
    school_name: 'MARTA VALLE HIGH SCHOOL'}
];